### PR TITLE
Added support for DC3231 battery backup clock module

### PR DESCRIPTION
**Pull request by nbJosh**
Added support for a battery backed up DS3231 over I2C.   Automatically since time with DS3231 at startup and when time is changed via buttons.

### CODE REVIEW

**Comment by nbJosh** [comment]
IMG_0955
IMG_0954
pictures of modification.   
as I was unpacking,  I did not see the nice feet you included in the package.   so I used some taller ones,  this left me room for the extra height of this full sized D3231 board.
I cut a hole in the bottom of the base,  and epoxied the DS3231 module in place with the battery accessible externally.

**Comment by afoxinsocks** [comment]
Wow, I'm really sorry the feet were missing in your package! Nice work. I'm hoping that once the mobile app is launched, a lack of battery backup won't be a large issue for most people, since the app will automatically sync time.

**Review by afoxinsocks — CHANGES_REQUESTED** [review]
These changes are definitely functional, although I'd rather see them in rtc_hal_apollo3.cpp, along with the define there. It looks like I'm missing a call to rtc_hal_init() in the setup() function (right after it starts) but if that were there, your backup code could run right out of rtc_hal_init. What do you think?

**Comment by nbJosh** [comment]
> Wow, I'm really sorry the feet were missing in your package! Nice work. I'm hoping that once the mobile app is launched, a lack of battery backup won't be a large issue for most people, since the app will automatically sync time.

To be clear,  you did include feet,  I didn't see them,  (Until after this mod was completed) ;)

**Comment by nbJosh** [comment]
Move the mods to RTC_Hal_apollo3,  and added a rtc_hal_init() in setup

**Comment by nbJosh** [comment]
And I missed a small bit.... but all resolved.   Will have to add day and date code to be compatible with eventually bluetooth app integration

**Review by afoxinsocks — APPROVED** [review]
Thanks for making these changes. I'll probably make a few more minor changes to move away from the h12 and PM globals (I'm pretty averse to using globals, even though they're common in arduino land) in the near future. Congratulations on being the first person to send a pull request!

**Pull request merged**
